#!/usr/bin/env bash
# a bash script displays To infinity and beyond indefinitely
# and displays I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' 15
while true
do
	echo "To infinity and beyond"
	sleep 2
done 
