#!/usr/bin/env bash
# This script displays Best School and when iterator equals 4 
# it displays bad luck and good luck when equals 8
i=1
# Check if the iterator equals a specific number
while [ $i -lt 11 ] 
do
	if [ "$i" -eq 4 ]; then
		echo "bad luck"
	elif [ "$i" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
